spring.application.name=API REST
# DESHABILITAR completamente la auto-configuración de BD
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

# Configuración del servidor
server.port=8080
spring.web.resources.add-mappings=true